org: jevill
service: serverless-api

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:GetItem
        - dynamodb:Scan
        - dynamodb:DeleteItem
      Resource:
        - arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.tableName}

functions:
  create:
    handler: src/create/create.handler
    events:
      - http:
          path: create
          method: post
  getAll:
    handler: src/getAll/getAll.handler
    events:
      - http:
          path: characters
          method: get
  deleteAll:
    handler: src/deleteAll/deleteAll.handler
    events:
      - http:
          path: characters
          method: delete

plugins:
  - serverless-offline

package:
  individually: true

custom:
  tableName: personajes-table
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    target: node18
    define:
      'require.resolve': undefined
    platform: node
    concurrency: 10

resources:
  Resources:
    PersonajesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: nombre
            AttributeType: S
        KeySchema:
          - AttributeName: nombre
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
